spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/oauth2_demo
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver # it wll help the spring to detect and use the best driver
  jpa:
    hibernate:
      # tell the app what to do on the startup
      ddl-auto: create-drop # start always with an empty database
    show-sql: false # when spring data jpa performs a query, it will be visible
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#logging.level.root=TRACE
#logging.level.org.springframework.security=DEBUG

franchise-client:
  client-id: breakwater-franchise-client
  client-secret: secret

backoffice-client:
  client-id: breakwater-backoffice-client
  client-secret: secret
logging:
  level:
    org:
      springframework:
        security: TRACE
