spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/auth
    username: postgres
    password: 2323

#  security:
#    oauth2:
#      client:
#        registration:
#          your-client:
#            client-id: your-client-id
#            client-secret: your-client-secret
#            scope: openid, profile
#            authorization-grant-type: authorization_code
#            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
#        provider:
#          your-provider:
#            authorization-uri: https://your-authorization-server/oauth/authorize
#            token-uri: https://your-authorization-server/oauth/token
#            user-info-uri: https://your-authorization-server/userinfo
#            jwk-set-uri: https://your-authorization-server/.well-known/jwks.json
#            issuer-uri: https://your-authorization-server
